/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';
import { rmSync, existsSync, mkdirSync } from 'node:fs';

/**
 * Vite configuration for @qwen-code/webui library
 *
 * Build outputs:
 * - ESM: dist/index.js (primary format)
 * - CJS: dist/index.cjs (compatibility)
 * - UMD: dist/index.umd.js (for CDN usage)
 * - TypeScript declarations: generated separately by `tsc -p tsconfig.dts.json`
 * - CSS: dist/styles.css (optional styles)
 */
export default defineConfig({
  plugins: [
    // On non-Windows, clean dist/ before building so stale .d.ts files
    // don't accumulate. On Windows we skip this entirely because any attempt
    // to delete or recreate dist/src/** triggers EPERM errors due to
    // antivirus/filesystem timing — declarations are generated by a separate
    // `tsc -p tsconfig.dts.json` step which is not affected by this issue.
    {
      name: 'clean-dist',
      buildStart() {
        if (process.platform === 'win32') return;
        const distPath = resolve(__dirname, 'dist');
        if (!existsSync(distPath)) return;
        try {
          rmSync(distPath, { recursive: true, force: true });
        } catch {
          // Non-fatal: Vite will overwrite existing files.
        }
      },
    },
    react(),
    {
      name: 'pre-create-dts-dir',
      closeBundle() {
        // Pre-create dist/src so the subsequent `tsc -p tsconfig.dts.json`
        // step can write .d.ts files without EPERM on Windows. Antivirus tools
        // briefly lock a newly created dist/ directory; creating dist/src here
        // (in the same process) avoids the first mkdir race in tsc.
        mkdirSync(resolve(__dirname, 'dist', 'src'), { recursive: true });
      },
    },
  ],
  build: {
    emptyOutDir: false,
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'QwenCodeWebUI',
      formats: ['es', 'cjs', 'umd'],
      fileName: (format) => {
        if (format === 'es') return 'index.js';
        if (format === 'cjs') return 'index.cjs';
        if (format === 'umd') return 'index.umd.js';
        return 'index.js';
      },
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
          'react/jsx-runtime': 'ReactJSXRuntime',
        },
        assetFileNames: 'styles.[ext]',
      },
    },
    sourcemap: true,
    minify: false,
    cssCodeSplit: false,
  },
});
