/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import { resolve } from 'path';
import { rmSync, existsSync } from 'node:fs';

/**
 * Vite configuration for @qwen-code/webui library
 *
 * Build outputs:
 * - ESM: dist/index.js (primary format)
 * - CJS: dist/index.cjs (compatibility)
 * - UMD: dist/index.umd.js (for CDN usage)
 * - TypeScript declarations: generated by vite-plugin-dts inside this process
 * - CSS: dist/styles.css (optional styles)
 */
export default defineConfig({
  plugins: [
    // On non-Windows, clean dist/ before building so stale files don't
    // accumulate. On Windows we skip this because rmSync on a freshly
    // created dist/ triggers EPERM due to antivirus/filesystem timing.
    {
      name: 'clean-dist',
      buildStart() {
        if (process.platform === 'win32') return;
        const distPath = resolve(__dirname, 'dist');
        if (!existsSync(distPath)) return;
        try {
          rmSync(distPath, { recursive: true, force: true });
        } catch {
          // Non-fatal: Vite will overwrite existing files.
        }
      },
    },
    react(),
    // Generate .d.ts files inside the Vite process to avoid the Windows EPERM
    // race that occurs when a separate `tsc` process tries to mkdir inside a
    // freshly created dist/ directory that antivirus is still scanning.
    dts({
      outDir: 'dist/src',
      tsconfigPath: './tsconfig.dts.json',
      include: ['src'],
      exclude: ['**/*.stories.tsx', '**/*.test.*'],
    }),
  ],
  build: {
    emptyOutDir: false,
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'QwenCodeWebUI',
      formats: ['es', 'cjs', 'umd'],
      fileName: (format) => {
        if (format === 'es') return 'index.js';
        if (format === 'cjs') return 'index.cjs';
        if (format === 'umd') return 'index.umd.js';
        return 'index.js';
      },
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
          'react/jsx-runtime': 'ReactJSXRuntime',
        },
        assetFileNames: 'styles.[ext]',
      },
    },
    sourcemap: true,
    minify: false,
    cssCodeSplit: false,
  },
});
