/**
 * @license
 * Copyright 2025 Qwen team
 * SPDX-License-Identifier: Apache-2.0
 */

// AUTO-GENERATED by scripts/inline_web_assets.js — do not edit manually.
// This file is overwritten before bundling. Committed as empty placeholder.
export const staticFiles: Record<string, { data: string; mime: string }> = {};
