/**
 * @license
 * Copyright 2025 Qwen team
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Reads packages/web-app/dist/ and writes packages/cli/src/web/staticFiles.ts
 * with all assets base64-encoded, so they can be bundled into the single .exe.
 *
 * Usage: node scripts/inline_web_assets.js
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DIST_DIR = path.join(ROOT, 'packages', 'web-app', 'dist');
const OUTPUT = path.join(
  ROOT,
  'packages',
  'cli',
  'src',
  'web',
  'staticFiles.ts',
);

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.json': 'application/json',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.png': 'image/png',
  '.map': 'application/json',
};

function walk(dir, base = '') {
  const entries = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const relPath = `${base}/${entry.name}`;
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      entries.push(...walk(fullPath, relPath));
    } else {
      entries.push({ relPath, fullPath });
    }
  }
  return entries;
}

if (!fs.existsSync(DIST_DIR)) {
  console.error(`[inline_web_assets] ERROR: ${DIST_DIR} not found.`);
  console.error('Run: npm run build --workspace=packages/web-app first.');
  process.exit(1);
}

const entries = walk(DIST_DIR);
const records = [];

for (const { relPath, fullPath } of entries) {
  const ext = path.extname(fullPath).toLowerCase();
  const mime = MIME[ext] ?? 'application/octet-stream';
  const data = fs.readFileSync(fullPath).toString('base64');
  records.push(
    `  ${JSON.stringify(relPath)}: { data: ${JSON.stringify(data)}, mime: ${JSON.stringify(mime)} }`,
  );
}

const totalKb = Math.round(records.join('').length / 1024);
console.log(
  `[inline_web_assets] Embedding ${entries.length} files (~${totalKb} KB source)`,
);

const output = `/**
 * @license
 * Copyright 2025 Qwen team
 * SPDX-License-Identifier: Apache-2.0
 */

// AUTO-GENERATED by scripts/inline_web_assets.js — do not edit manually.
// Regenerated as part of "npm run bundle" before esbuild runs.
export const staticFiles: Record<
  string,
  { data: string; mime: string }
> = {
${records.join(',\n')}
};
`;

fs.writeFileSync(OUTPUT, output, 'utf8');
console.log(`[inline_web_assets] Written to ${path.relative(ROOT, OUTPUT)}`);
